url: https://youngsam-byun.github.io
baseurl: /my-notes.github.io
remote_theme: just-the-docs/just-the-docs
title: programming notes and ...
footer_content: "Copyright &copy; 2022- <a href=\"https://www.linkedin.com/in/youngsam-byun-54456370/?originalSubdomain=sg\">Youngsam Byun</a>"

disqus_shortname: https-youngsam-byun-github-io-my-notes-github-io